# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install gfortran for Linux
      run: sudo apt-get install gfortran

    - name: Check gfortran version
      run: gfortran --version

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: get a copy of giza
      run: git clone https://github.com/danieljprice/giza

    - name: compile splash
      run: make SYSTEM=gfortran withgiza

    - name: clean
      run: make clean

    - name: compile libexact
      run: make SYSTEM=gfortran libexact

    - name: compile libread
      run: make SYSTEM=gfortran libread
