# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain:
          - {compiler: gcc,   version: 'latest', system: gfortran}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libhdf5-dev libcfitsio-dev
          git clone https://github.com/danieljprice/giza
          make SYSTEM=gfortran withgiza
          cd 
          git clone https://github.com/danieljprice/phantom.git
          export OMP_SCHEDULE="dynamic"
          export OMP_STACKSIZE=512M
          ulimit -s unlimited
          export SYSTEM=gfortran
          
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install cairo libx11 freetype hdf5 cfitsio
        fi

    - name: Check files
      run: |
        cd
        pwd
        ls
